package com.example.data.exceptions;

/**
 * An inserted or updated object shares a primary or unique key with one that already exists
 * <p>
 * As IDs are autogenerated this currently only applies to Supplier names.
 */
public class UniqueViolation extends DataException {
    public UniqueViolation(String s, Exception exception) {
        super(s, exception);
    }
}
